site_name: Aiosteampy
site_url: https://aiosteampy.somespecial.one
site_author: Dmytro Tkachenko
site_description: Simple library to trade and interact with steam market, webapi, guard.

repo_name: aiosteampy
repo_url: https://github.com/somespecialone/aiosteampy

copyright: Copyright &copy; 2022 - 2023 Dmytro Tkachenko

theme:
  name: material
  custom_dir: docs/theme
  logo: logo.svg
  favicon: logo.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/file-document-edit-outline

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/light-switch-off
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/light-switch
        name: Switch to dark mode

extra_css:
  - theme/extra.css

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/aiosteampy/
    - icon: fontawesome/brands/github
      link: https://github.com/somespecialone
    - icon: fontawesome/solid/envelope
      link: mailto:tkachenkodmitriy@yahoo.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/somespecialone/
    - icon: fontawesome/solid/globe
      link: https://somespecial.one

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Install: install.md
  - 'Getting started 🚀': get_started.md
  - Client: client.md
  - Market: market.md
  - Trade: trade.md
  - Public: public.md
  - States&cache: states.md
  - Examples:
      - 'states mixin': examples/states.md
      - 'session persistence': examples/session.md
      - '3rd party sites auth': examples/auth_3rd_party_site.md
  - 'Testing 🧪': tests.md
