name: Docs

on:
  push:
    branches:
      - master
    paths: ["mkdocs.yml", "docs/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install --only docs

      - name: "Building and deploying docs to GitHub Pages"
        run: poetry run mkdocs gh-deploy --force
